# Dirs
data:
  base_root: "data"
  dirs:
    raw: "raw"
    references: "references"
    index: "hisat_index"
    trimmed: "trimmed"

output:
  base_root: "output"
  dirs:
    mapped: 'mapped'

qc:
  base_root: "QC"
  dirs:
    mapping: 'mapping'
    raw: 'raw'
    trimmed: 'trimmed'

workflow:
  base_root: "workflow"
  dirs:
    rules: "rules"
    scripts: "scripts"
    lib: "lib"

# Files
sra:
  - SRR11647685  # GSM4505876
  - SRR11647686  # GSM4505877
  - SRR11647687  # GSM4505878
  - SRR11647695  # GSM4505886
  - SRR11647696  # GSM4505887
  - SRR11647697  # GSM4505888

ref:
  annotation:
    link: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.primary_assembly.annotation.gtf.gz"
    file_name: "gencode_annotation_v49.gtf"
  genome: 
    link: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/GRCh38.primary_assembly.genome.fa.gz"
    file_name: "homo_GRCh38_ref.fa"
  bed_annotation:
    link: "https://sourceforge.net/projects/rseqc/files/BED/Human_Homo_sapiens/hg38_GENCODE_V47.bed.gz"
    file_name: "hg38_GENCODE_V47.bed"

suffix:
  fasta: 'fasta'
  fastq: 'fastq'
  report: 'html'
  compress: 'gz'

qc_plots:
  - 'correlation'
  - 'pca'
  - 'mapping_rates'
  - 'all.geneBodyCoverage.curves'
  - 'all.clipping_profile'
  - 'all.inner_distance'
  - 'all.junction_annotation'

# States
paired_id:
  - 1
  - 2

# Program's params
fasterq_params:
  threads: 3

fastqc_params:
  threads: 3

hisat-build_params:
  threads: 6
  seed: 1
  prefix: 'hisat2_index'

mapping_qc_params:
  script: workflow/scripts/plot_mapping_rates.py